### PR TITLE
Rename RGB1->XRGB, RGB4->RGBX

### PR DESCRIPTION
**Pull request by timholy**
I realized we should do this sooner than later, to give other packages time to deal with deprecation warnings. When we release 1.0 we should eliminate the deprecations.

### CODE REVIEW

**Comment by tknopp** [comment]
@timholy: Were there any deprecation warnings?

**Comment by timholy** [comment]
Of course :smile:

**Comment by tknopp** [comment]
Hm, was that ironic? People are running through my institute reporting that something broke and we were able tracking it down to hear. I then read your OP, which sounded that deprecation warnings actually should have been emitted.

**Comment by timholy** [comment]
Definitely not ironic. You know you can check the `Files changed` tab yourself without having to ask---the depwarns are in the top few lines of `ColorTypes.jl`.

Some folks don't think of depwarns as breaking, but we bumped the minor version number anyway. If you're using upper bounds on package versions, as is recommended now, nothing should have changed until you were ready to upgrade.

More specifics about the breakage would be useful. The only thing that should break is performance (which will go into the toilet until you change the names).

**Comment by tknopp** [comment]
> Definitely not ironic. You know you can check the Files changed tab yourself without having to ask---the depwarns are in the top few lines of ColorTypes.jl.

Sorry, I actually did exactly that, but for some reason did oversaw them, sorry! 

The upper bounds thing is clear, but we might have done something wrong in this package https://github.com/tknopp/ImageUtils.jl. Will have a look myself before I can give a better informed answer.

**Comment by timholy** [comment]
There's another possible issue: if you get these via `using Colors` (rather than `using ColorTypes`) it looks like `@reexport` doesn't automatically export the deprecated names. Try upgrading to https://github.com/JuliaGraphics/Colors.jl/pull/383.

**Comment by timholy** [comment]
It's bizarre, that package depends on Colors which shouldn't have allowed the upgrade without https://github.com/JuliaGraphics/Colors.jl/pull/383.

Oh, wait, I bet this is a registry bug, see https://github.com/JuliaRegistries/General/pull/6834

**Comment by tknopp** [comment]
Here is the travis log that shows the error

https://travis-ci.org/tknopp/ImageUtils.jl/jobs/626828413

**Comment by tknopp** [comment]
So was the bug that Colors had no upper bound and therefore claimed to be compatible with future ColorTypes? Because ImageUtlis should only have a version contract with Colors not ColorTypes.

**Comment by tknopp** [comment]
This is actually a very interesting case that showcases an important scalability use case.

I think of Colors (or Images) as a metapackage that is responsible for keeping a consistent interface. These metapackge will be even more important in the "upper bound" scenario, since they are responsible for not breaking the interfaces. Thus, new changes first need to be tested in the metapackage, which makes only a release with larger upper bounds, one all of its tests pass.

**Comment by tknopp** [comment]
There is still something wrong:

https://travis-ci.org/tknopp/ImageUtils.jl/jobs/626828416

The issue comes from ImageCore.

**Comment by timholy** [comment]
https://github.com/JuliaRegistries/General/pull/6903

**Comment by timholy** [comment]
That's merged now, you could try again.

**Comment by tknopp** [comment]
I don't know if I need to do something specific but just restarting travis, the error persists:

https://travis-ci.org/tknopp/ImageUtils.jl/jobs/626828413

**Comment by timholy** [comment]
Dang. https://github.com/JuliaRegistries/General/pull/6905

**Comment by timholy** [comment]
That was very sneaky of the resolver to install ImageCore 0.8.2. Without an algorithm to set these retrospective bounds, I am not entirely confident of my ability to block all possible escape hatches.

**Comment by tknopp** [comment]
you got it: https://travis-ci.org/tknopp/ImageUtils.jl

**Pull request merged**
