### PR TITLE
fix depwarns under 0.7 and bump REQUIRE and CI to 0.6

### PR DESCRIPTION
**Pull request by Sacha0**
Best! :)

### CODE REVIEW

**Comment by timholy** [comment]
Sure, seems like time to move on. Thanks!

**Comment by lobingera** [comment]
and 0.5 users?

**Comment by ararslan** [comment]
People on 0.5 can continue to use the last tagged version that supports 0.5. If something needs fixing, you can branch from the last 0.5 tag, cherry-pick commits from master, and do another 0.5-supporting release.

**Comment by Sacha0** [comment]
Thanks all! :)

**Comment by lobingera** [comment]
@ararslan Maybe i'm a little bit over sensitive on this, but as ColorTypes is a requirement for Colors and this in turn is a requirement for almost everything that plots/draws/paints something; isn't this one of the cases where a simple Pkg.update() in 0.5 can filp you whole package repository to unusable?

**Comment by timholy** [comment]
No, since you can't install the 0.6.x series of ColorTypes, you'll continue to use the 0.5.x series as long as you're relying on `Pkg.update()` and not following `master`. (Use `Pkg.free()` if necessary.)

**Pull request merged**
