### PR TITLE
Fix Lab gamut (#84)

### PR DESCRIPTION
**Pull request by oxinabox**
This just adds the conclusions from the discussion of #84.

Can anyone think of a good set of tests?

### CODE REVIEW

**Comment by timholy** [comment]
Other than directly testing the same values entered in source, the only "consumer" is `rand`. So the only easy way to test would be to generate lots of random numbers. We could conceivably add a test to see how much of RGB space gets filled by `[convert(RGB, rand(C)) for i = 1:10^4]` for all the `C` types, but that's not entirely easy.

Any ideas, @bjarthur?

**Comment by bjarthur** [comment]
not really.  perhaps @m-lohmann has some?

**Comment by timholy** [comment]
I'm inclined to merge this without tests, just to avoid causing @oxinabox any hassle from merge conflicts with #92. Seem OK?

**Comment by bjarthur** [comment]
fine with me

**Comment by timholy** [comment]
Thanks, @oxinabox!

**Pull request merged**
