### PR TITLE
[CI] switch from Travis to Github Action

### PR DESCRIPTION
**Pull request by johnnychen94**
Changes:

* use GitHub Actions for unit test and code coverage
* add test for Windows
* caching artifacts

closes #204

### CODE REVIEW

**Comment by kimikage** [comment]
The following seems to be available in public repositories.
https://github.com/invenia/PkgTemplates.jl/blob/aeff1f3c231626c4854d9c2b0e158c3e9073aa73/templates/github/workflows/ci.yml#L52-L55

**Comment by johnnychen94** [comment]
Currently, Github action isn't well suited for code coverage report:

1) it requires the maintainer to _manually_ set secret environment `COVERALLS_TOKEN` or `CODECOV_TOKEN`
2) fork repo can't read secrets, which means PRs from other forks can't successfully upload coverage report

**Comment by kimikage** [comment]
Is it really "current"?
https://community.codecov.io/t/whitelist-github-action-servers-to-upload-without-a-token/491/17
https://github.com/julia-actions/julia-uploadcodecov/issues/1#issuecomment-608043596

**Comment by johnnychen94** [comment]
I thought I have subscribed to that issue but apparently I didn't. Will update it later.

**Comment by johnnychen94** [comment]
This doesn't involve any functionality changes to the package, so whether using it purely depends on how maintainers feel about it. Given that [Github Action allows 20 (or more) concurrent jobs](https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits), it significantly reduces the CI queueing time and thus I prefer to use it when possible.

Similar changes are done to https://github.com/JuliaGraphics/Colors.jl/pull/433 and https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/132

**Comment by kimikage** [comment]
@johnnychen94, thank you for your contribution to efficient development!

**Pull request merged**
