### PR TITLE
Remove old deprecations

### PR DESCRIPTION
**Pull request by timholy**
See https://github.com/JuliaGraphics/ColorTypes.jl/pull/81#issuecomment-294139027. I added some tests to make sure the behavior we were trying to avoid doesn't get re-added.

### CODE REVIEW

**Comment by tkelman** [comment]
Could do a grep through pkgeval logs to see who hasn't fixed these yet? what should be searched for? it's all public in the website repo https://github.com/JuliaCI/pkg.julialang.org but the abuse of git there means it's probably a huge repo to clone

**Comment by timholy** [comment]
Good grep strings:
```
use reinterpret(RGB24
use reinterpret(Gray24
use reinterpret(ARGB32
use reinterpret(AGray32
use reinterpret(UInt32,x) == y
use x == reinterpret(UInt32,y)
```
I already have a fix for Images (https://github.com/JuliaImages/Images.jl/pull/634), so don't worry about that.

**Comment by tkelman** [comment]
ImageMagick on 0.4 hits it, but apparently nothing else

**Comment by timholy** [comment]
Since all recent versions of ImageMagick require julia 0.5, I think we're fine.

**Pull request merged**
