### PR TITLE
Export types used in other packages of the Images.jl project

### PR DESCRIPTION
**Pull request by juliohm**
This PR exports missing types used in other packages of the Images.jl project. I appreciate if you can review and merge. I will submit another PR to Colors.jl and Images.jl meanwhile.

### CODE REVIEW

**Comment by Evizero** [comment]
xref: https://github.com/JuliaImages/Images.jl/issues/731

**Comment by timholy** [comment]
Ideally one would add a test that these exports are available, but if you're OK risking that someone else will come along and unexport them, we could merge this.

**Comment by juliohm** [comment]
That is a great idea, how to implement such test? What function in Julia can be used to check for names exported?

**Comment by timholy** [comment]
Many possibiliites. You could use `isa`, but I kind of like
```julia
dispatcher(::AbstractGray) = 1
dispatcher(::TransparentGray) = 2
...
@test dispatcher(Gray(0.2)) == 1
@test dispatcher(AGray(0.2, 0.5)) == 2
...
```

**Comment by juliohm** [comment]
@timholy added tests to all types except for `Transparent3` and `ColorantNormed`. Could you please clarify which concrete types implement the concept?

**Comment by timholy** [comment]
`ColorantNormed{T<:Normed,N} = Colorant{T,N}` just means any Colorant using Normed numbers (e.g., `N0f8`) as its eltype. 

`Transparent3{C<:Color3,T} = TransparentColor{C,T,4}` means a colorant that has transparency and its base color is a `Color3`. A good example is `RGBA`.

**Comment by juliohm** [comment]
@timholy `RGBA` dispatches to `TransparentRGB` instead of `Transparent3`. Is there another concrete type that is not RGB that I could use in the test?

**Comment by juliohm** [comment]
Also, how we can test the `ColorantNormed` case?

**Comment by Evizero** [comment]
> Also, how we can test the ColorantNormed case?

 maybe something like

```julia
julia> using ColorTypes, FixedPointNumbers

julia> RGB{N0f8}(0,0.1, 0.5)
RGB{N0f8}(0.0,0.102,0.502)

julia> dispatcher(::ColorTypes.ColorantNormed) = 3
dispatcher (generic function with 1 method)

julia> dispatcher(::ColorTypes.Colorant) = 4
dispatcher (generic function with 2 methods)

julia> dispatcher(RGB{N0f8}(0.,0.1,0.5))
3

julia> dispatcher(RGB{Float32}(0.,0.1,0.5))
4
```

**Comment by Evizero** [comment]
> `RGBA` dispatches to `TransparentRGB` instead of `Transparent3`. Is there another concrete type that is not RGB that I could use in the test?

found one:

```julia
julia> alphacolor(rand(HSV))
AHSV{Float64}(354.887716223749,0.259748993210698,0.7149158244136269,1.0)

julia> alphacolor(rand(HSV)) isa ColorTypes.TransparentRGB
false

julia> alphacolor(rand(HSV)) isa ColorTypes.Transparent3
true
```

**Comment by juliohm** [comment]
Thank you @Evizero , for the `ColorantNormed` example you shared, it is dispatching on `Color3` with higher priority. Do you suggest another type?

**Comment by juliohm** [comment]
Maybe the `ColorantNormed` doesn't need to exist? The dispatcher seems to always give priority to other types. I appreciate if you can clarify the issue.

**Comment by Evizero** [comment]
I don't have a good answer to that.

Maybe the following test is good enough

```julia
@test RGB{N0f8} <: ColorantNormed
@test !(RGB{Float32} <: ColorantNormed)
```

**Comment by timholy** [comment]
Or use a new function
```julia
normeddispatcher(::ColorantNormed) = 1
normeddispatcher(::Colorant) = 2
```

**Comment by juliohm** [comment]
Awesome! The PR should be ready to merge. Thanks for all the suggestions.

**Comment by timholy** [comment]
Thank you!

**Pull request merged**
