### PR TITLE
Backport recent commits to v0.11

### PR DESCRIPTION
**Pull request by stillyslalom**
It's been more than a year since the last release. I've pulled commits since then into the v0.11 backport branch.

Looks like CI isn't running automatically - does a committer need to trigger the tests?

### CODE REVIEW

**Comment by stillyslalom** [comment]
@timholy @johnnychen94: how can I trigger CI? Tests pass locally.

**Comment by stillyslalom** [comment]
Bumping this again... any takers?

**Comment by johnnychen94** [comment]
Sorry, daily work is too busy for me...

local test is good, merging.

**Comment by johnnychen94** [comment]
There's some issue with StyledStrings (#293) as it's a stdlib in Julia 1.11+, I'll revert that commit and re-register it.

https://github.com/JuliaGraphics/ColorTypes.jl/commit/5eea76d589f4f3c3012e3d16199a9bb1f1cabcbb#comments

**Comment by johnnychen94** [comment]
released: https://github.com/JuliaRegistries/General/pull/104367

**Pull request merged**
